web/cfd/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('fourth_umpire.urls')),
]

web/fourth_umpire/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.main, name='main'),

    url(r'^main/$', views.main, name='main2'),

    url(r'^pred/$',views.prediction),

    url(r'^index/$',views.index,name='index'),

    url(r'^main/serve/$', views.main, name='mainpred'),

    url(r'^about/$', views.about, name='about'),

    url(r'^gallery/$', views.flowchart, name='gallery'),

    url(r'^contact/$', views.contact, name='contact'),

    url(r'^first_inn/$', views.first_inn, name='first_inn'),

    # url(r'^second_inn/$', views.second_inn, name='secustom_processcond_inn'),
    url(r'^pre_pred/$', views.prematch, name='prematch'),

    url(r'^customise',views.customise,name='customise'),

    url(r'^process/$',views.customise_process,name='custom_process'),

    url(r'^getdata/$',views.get_data,name='get'),

    url(r'^getteam1/$',views.get_team1,name='team1'),

    url(r'^season_customise/$',views.season_customise,name='season_customise'),

    url(r'^season_process/$', views.season_customise_process, name='season_customise_process'),

    url(r'^fetch_teams/$',views.fetch_teams,name='fetch_teams'),

    url(r'^show/$',views.show_template,name=''),
]

web/fourth_umpire/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Match(models.Model):
    team1 = models.CharField(max_length=30)
    team2 = models.CharField(max_length=30)

web/fourth_umpire/forms.py
from django import forms
from .models import Match

team_choice = (
        (1,	'Sunrisers Hyderabad'),
        (2,	'Royal Challengers Bangalore'),
        (3,	'Chennai Super Kings'),
        (4,	'Kings XI Punjab'),
        (5,	'Rajasthan Royals'),
        (6,	'Delhi Daredevils'),
        (7,	'Mumbai Indians'),
        (8,	'Kolkata Knight Riders'),
)

city_choice = (
    (1	, 'Hyderabad'),
    (2	, 'Pune'),
    (3	, 'Rajkot'),
    (4	, 'Indore'),
    (5	, 'Bangalore'),
    (6	, 'Mumbai'),
    (7	, 'Delhi'),
    (8	, 'Chennai'),
    (9	, 'Sharjah'),
    (10	, 'Ranchi'),
    (11	, 'Patna'),
    (12	, 'Kolkata'),
    (13	, 'Chandigarh'),
    (14	, 'Kanpur'),
    (15	, 'Jaipur'),
    (24	, 'Ahmedabad'),
    (25	, 'Cuttack'),
    (26	, 'Nagpur'),
    (27	, 'Dharamsala'),
    (28	, 'Kochi'),
    (29	, 'Visakhapatnam'),
    (30	, 'Raipur'),
)

class PreMatch(forms.Form):
    team1 = forms.ChoiceField(choices=team_choice, widget=forms.Select())
    team2 = forms.ChoiceField(choices=team_choice, widget=forms.Select())
    venue = forms.ChoiceField(choices=city_choice, widget=forms.Select())


class InningsFirst(forms.Form):
    team1 = forms.ChoiceField(choices=team_choice, widget=forms.Select(),label="Batting Team")
    team2 = forms.ChoiceField(choices=team_choice, widget=forms.Select(),label="Bowling Team")
    venue = forms.ChoiceField(choices=city_choice, widget=forms.Select())
    runs = forms.IntegerField()
    overs_played = forms.IntegerField()
    wickets_fallen = forms.IntegerField()

class InningsSecond(forms.Form):
    team1 = forms.ChoiceField(choices=team_choice, widget=forms.Select(),label="Current Batting Team")
    team2 = forms.ChoiceField(choices=team_choice, widget=forms.Select(),label="Current Bowling Team")
    venue = forms.ChoiceField(choices=city_choice, widget=forms.Select())
    runs = forms.IntegerField()
    wickets_fallen = forms.IntegerField()
    overs_played = forms.IntegerField()
    target_set = forms.IntegerField()

web/fourth_umpire/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .prediction import predict
import requests
import pandas as pd
import csv
from _pydecimal import Decimal
import operator
from numpy import unicode

winner_list = []
Eigen_score = []
result = []
season_result = []
test = []
players =[]
Eigen_1 = []
Eigen_2 = []
Eigen_3 = []
Eigen_list = []
custom_winner_list = []

# checking
from django.shortcuts import render, render_to_response

from bokeh.plotting import figure, output_file, show
from bokeh.embed import components
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib.dates import DateFormatter

from bokeh.plotting import figure
from bokeh.resources import CDN
from bokeh.embed import components


def show_template(request):
    return render(request, 'fourth_umpire/player_swap.html')


def season_customise(request):
    print("year ", request.POST['year24'])
    season = request.POST['year24']

    context = {
        'season': season,
    }

    return render(request, 'fourth_umpire/player_swap.html', context)


def season_customise_process(request):

    print("post data ",request.POST)

def fetch_teams(request):
    print("season ", request.GET.get('season'))
    f = open('fourth_umpire/Dataset/results.csv')
    csv_f = csv.reader(f)
    next(csv_f)
    team_list = [];
    other_teams = {}
    for row in csv_f:
        team = row[0]
        team_list.append(team)
        players = list(row[1].split(','))
        for x in range(0, len(players)):
            other_teams[team] = list(row[1].split(','))

    data = {
        'other_teams': other_teams,
        'team':team_list,
    }

    return JsonResponse(data)


def index(request):
    # df = pd.read_csv('fourth_umpire/Dataset/_team_rank.csv')
    # print(df)
    # for row in df:
    #     print(row)
    # GUJARAT
    x = []
    y = []
    a = []
    with open('fourth_umpire/Dataset/_team_rank.csv', 'r') as csvfile:
        next(csvfile)
        plots = csv.reader(csvfile, delimiter=',')
        for row in plots:
            x.append(row[0])
            y.append(row[1])

    for team in x:
        if team == "Chennai Super Kings":
            a.append('CSK')

        if team == "Mumbai Indians":
            a.append('MI')

        if team == "Rajasthan Royals":
            a.append('RR')

        if team == "Kolkata Knight Riders":
            a.append('KKR')

        if team == "Delhi Daredevils":
            a.append('DD')

        if team == "Royal Challengers Bangalore":
            a.append('RCB')

        if team == "Kings XI Punjab":
            a.append('KXIP')

        if team == "Deccan Chargers":
            a.append('DC')

        if team == "Pune Warriors":
            a.append('PW')

    print("teams ", a)
    print("eigens ", y)

    # x = ['MI', 'CSK', 'KKR', 'RCB', 'SRH', 'DD', 'KXIP', 'RR']
    p = figure(x_range=a, plot_height=250, title="Team rank based on eigen score")
    p.vbar(x=a, top=y, width=0.9)

    p.xgrid.grid_line_color = None
    p.y_range.start = 0
    script, div = components(p, CDN)

    #
    # print(script)
    # print(div)
    # show(p)
    # output_file('fourth_umpire/templates/fourth_umpire/c.html')

    return render_to_response('fourth_umpire/c.html',
                              {'script': script, 'div': div, }
                              )


# checking


def main(request):
    return render(request, 'fourth_umpire/main.html')


def about(request):
    return render(request, 'fourth_umpire/about.html')


def contact(request):
    return render(request, 'fourth_umpire/contact.html')


def flowchart(request):
    return render(request, 'fourth_umpire/gallery.html')


def test(request):
    return render(request, 'fourth_umpire/remove_player.html')


def prediction(season):
    url = 'http://www.cricmetric.com/ipl/ranks/' + season
    pd.read_html(requests.get(url).content)[-1].to_csv("fourth_umpire/Dataset/_player_rank.csv", index=False)
    url = 'http://www.cricmetric.com/series.py?series=ipl' + season + '&show=matches'
    pd.read_html(requests.get(url).content)[0].to_csv("fourth_umpire/Dataset/match_list.csv", index=False)
    # url = 'https://www.sportskeeda.com/go/ipl/points-table'
    # pd.read_html(requests.get(url).content)[0].to_csv("test.csv", index=False)
    data = pd.read_csv("fourth_umpire/Dataset/_player_rank.csv")
    team_rank = pd.DataFrame(
        data.groupby('Team')['EFscore'].agg(['sum']).reset_index().sort_values('sum', ascending=False)).to_csv(
        "fourth_umpire/Dataset/_team_rank.csv", index=False)
    df = pd.read_csv('fourth_umpire/Dataset/_team_rank.csv')
    # fig = px.bar(df, x='Team', y='sum', title='Team Rankings based on eigen score For Season -' + season)
    # fig.write_image("./images/fig1.png")
    # fig.show()

    # these 3 lines have to work rankings csv file not found

    # data = pd.read_csv('fourth_umpire/Dataset/rankings.csv')
    # rankings = data.groupby(['Team']).sum()
    # export_csv = rankings.to_csv(r'fourth_umpire/Dataset/results.csv')

    # response = HttpResponse(mimetype="./images/fig1.png")
    # fig.save(response, "PNG")
    with open('fourth_umpire/Dataset/_team_rank.csv', 'rt')as f:
        data = csv.reader(f)
        for row in data:
            winner_list.append(row[0])
            Eigen_score.append(row[1])
    print("The Predicted winner Team " + "for the season " + season + " is ---------- " + winner_list[
        1] + " ------------ With Eigen Score Of " + Eigen_score[1])

    f = open('fourth_umpire/Dataset/results.csv')
    csv_f = csv.reader(f)
    for row in csv_f:
        team = row[0]
        players = list(row[1].split(','))
        print("ss ", len(players))
        print("t ", team)
        for x in range(0, len(players)):
            # print("x ", x)
            #             # test.update({players[x]: team})
            with open('fourth_umpire/Dataset/create.csv', 'a') as fd:
                fd.write(team)
                fd.write(',')
                fd.write(players[x])
                fd.write('\n')

def customise(request):
    print("year ", request.POST['year23'])
    season = request.POST['year23']
    prediction(season)
    f = open('fourth_umpire/Dataset/match_list.csv')
    csv_f = csv.reader(f)
    next(csv_f)

    context = {
        'csv': csv_f,
        'season': season,
    }
    return render(request, 'fourth_umpire/customize.html', context)


def customise_process(request):
    # print(request.POST)
    player1 = request.POST.getlist('player1')
    player2 = request.POST.getlist('player2')
    match_no = request.POST['Match_No']
    f = open('fourth_umpire/Dataset/match_list.csv')
    csv_f = csv.reader(f)
    for row in csv_f:
        if (row[0] == match_no):
            actual_winner = row[5]
    venue = request.POST['venue']
    toss_win = request.POST['toss_win']
    toss_decision = request.POST['toss']
    team1 = request.POST['team1']
    team2 = request.POST['team2']
    weather = request.POST['weather']
    season = request.POST['year']
    print("match_no", match_no)
    print("venue", venue)
    print("toss_win", toss_win)
    print("toss_desicion", toss_decision)
    print("weather", weather)
    print("season ", season)
    f = open('fourth_umpire/Dataset/_player_rank.csv')
    csv_f = csv.reader(f)
    for row in csv_f:
        for i in range(len(player1)):
            if (row[1] == player1[i]):
                Eigen_1.append(Decimal(row[5]))
            if (row[1] == player2[i]):
                Eigen_2.append(Decimal(row[5]))
    t1 = sum(Eigen_1)
    t2 = sum(Eigen_2)
    # for home ground privilages
    if ((team1 == 'Chennai Super Kings') and (venue == '8')):
        t1 = float(t1) + 0.25 * float(t1)
    if ((team1 == 'Deccan Chargers') and (venue == '1')):
        t1 = float(t1) + 0.25 * float(t1)
    if ((team1 == 'Delhi Daredevils') and (venue == '7')):
        t1 = float(t1) + 0.25 * float(t1)
    if ((team1 == 'Kings XI Punjab') and (venue == '13')):
        t1 = float(t1) + 0.25 * float(t1)
    if ((team1 == 'Kolkata Knight Riders') and (venue == '12')):
        t1 = float(t1) + 0.25 * float(t1)
    if ((team1 == 'Mumbai Indians') and (venue == '6')):
        t1 = float(t1) + 0.25 * float(t1)
    if ((team1 == 'Rajasthan Royals') and (venue == '15')):
        t1 = float(t1) + 0.25 * float(t1)
    if ((team1 == 'Royal Challengers Bangalore') and (venue == '5')):
        t1 = float(t1) + 0.25 * float(t1)
    if ((team2 == 'Chennai Super Kings') and (venue == '8')):
        t2 = float(t2) + 0.25 * float(t2)
    if ((team2 == 'Deccan Chargers') and (venue == '1')):
        t2 = float(t2) + 0.25 * float(t2)
    if ((team2 == 'Delhi Daredevils') and (venue == '7')):
        t2 = float(t2) + 0.25 * float(t2)
    if ((team2 == 'Kings XI Punjab') and (venue == '13')):
        t2 = float(t2) + 0.25 * float(t2)
    if ((team2 == 'Kolkata Knight Riders') and (venue == '12')):
        t2 = float(t2) + 0.25 * float(t2)
    if ((team2 == 'Mumbai Indians') and (venue == '6')):
        t2 = float(t2) + 0.25 * float(t2)
    if ((team2 == 'Rajasthan Royals') and (venue == '15')):
        t2 = float(t2) + 0.25 * float(t2)
    if ((team2 == 'Royal Challengers Bangalore') and (venue == '5')):
        t2 = float(t2) + 0.25 * float(t2)
    # toss win and weather conditions
    if (toss_win == '1'):
        if (toss_decision == '1'):
            if ((weather == '1') or (weather == '2')):
                t1 = float(t1) + 0.25 * float(t1)
            else:
                t1 = float(t1) - 0.25 * float(t1)
        else:
            if ((weather == '3') or (weather == '4') or (weather == '5')):
                t1 = float(t1) + 0.25 * float(t1)
            else:
                t1 = float(t1) - 0.25 * float(t1)
    else:
        if (toss_decision == '1'):
            if ((weather == '1') or (weather == '2')):
                t2 = float(t2) + 0.25 * float(t2)
            else:

web/fourth_umpire/templates/fourth_umpire/b.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Bokeh Scatter Plots</title>
   <link rel="stylesheet" href="http://cdn.pydata.org/bokeh/release/bokeh-0.9.0.min.css" type="text/css" />
      <script src="https://cdn.pydata.org/bokeh/release/bokeh-1.3.2.min.js"></script>
<script src="https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.3.2.min.js"></script>
<script src="https://cdn.pydata.org/bokeh/release/bokeh-tables-1.3.2.min.js"></script>
 </head>
 <body>
     {{ div | safe }}
</body>
    <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-0.9.0.min.js"></script>
    {{ script | safe }}
</html>

web/fourth_umpire/templates/fourth_umpire/c.html




<!DOCTYPE html>
<html lang="en">

  <head>

      <meta charset="utf-8">
      <title>Bokeh Plot</title>







        <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-1.3.2.min.js"></script>
        <script type="text/javascript">
            Bokeh.set_log_level("info");
        </script>




  </head>


  <body>

  {{div|safe}}


  {{script|safe}}




  </body>

</html>

web/fourth_umpire/templates/fourth_umpire/firstinn.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Indian Premier League|Match Predictor</title>
    <!-- Meta Tags -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}




    </script>


    <!-- //Meta Tags -->
    <!-- Style Sheets -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <!--// Bootstrap-CSS -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <!--// Font-Awesome-CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <!-- //Style Sheets -->
    <!-- web-fonts -->
    <link href="//fonts.googleapis.com/css?family=Khula:300,400,600,700,800" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,400,400i,500,500i,600,600i,700,700i,800"
          rel="stylesheet">
    <!--// web-fonts -->
</head>

<body>
<!-- banner -->
<div class="banner-1 jarallax" id="home">
    <header>
        <div class="container">
            <div class="header-bottom-agileits">
                <div class="w3-logo">
                    <h1><a href="{% url 'main2' %}">THE IPL SEASON PREDICTOR</a></h1>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </header>
    <!-- navigation -->
    <div class="nav-bg">
        <div class="container">
            <nav class="navbar navbar-default shift">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1"
                            aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'main2' %}">HOME</a></li>
                        <li><a href='#serve'>PREDICTIONS</a></li>
                        <li><a class="active" href="{% url 'about' %}">ALGORITHMS</a></li>
                        <li><a href="{% url 'gallery' %}">FLOWCHART</a></li>
                        <li><a href="{% url 'contact' %}">CONTACT</a></li>
                    </ul>

                </div>
                <!-- /.navbar-collapse -->

            </nav>
        </div>
    </div>
    <!-- //navigation -->
</div>
<!-- //banner -->
<!-- about -->
<div class="about">
    <div class="container">
        <div class="wthree_head_section">
            <h3 class="w3l_header"> MATCH <span>PREDICTOR</span></h3>
            <p>You can now check the winner of any match, of any season,
                also make the changes you wish to... and then check the result of the match</p>
            <p>Enter the match number of any season</p>
            <p>Make the tweaks you wish to make in the team and the venue</p>
            <p>Also the toss result can be changed</p>
            <p>Check the winner of the match by clicking the submit button</p>
            <p>See the changes occurring in the match with the tweaks you have made</p>


            <form action="" method="post">
                {%csrf_token%}
                <div class="text-align-center">
                <div class="colo">
                     {% if message %}
                             <center><b> {{message}}</b></center>
                             {%endif%}
                </div>
                    </div>

                <div class="match">

                    <br>
                    <br>
                    <div class="form-group">

                        <label class="control-label" for="id_team1">Team-1</label>
                        <div class="">
                            <select name="team1" class=" form-control" id="id_team1"
                                    onchange="checkSameTeam(this.value);getStadium(this.value);">
                                <option value="Mumbai">MI</option>
                                <option value="Kolkata">KKR</option>
                                <option value="Bangalore">RCB</option>
                                <option value="Pune">CSK</option>
                                <option value="Jaipur">RR</option>
                                <option value="Delhi">DD</option>
                                <option value="Dharamshala">KXIP</option>
                                <option value="Hyderabad">SRH</option>
                            </select>
                        </div>
                    </div>
                    <br>
                    <br>
                    <div class="form-group">
                        <label class="control-label" for="id_team2">Team-2</label>
                        <div class=" ">
                            <select name="team2" class=" form-control" id="id_team2"
                                    onchange="checkSameTeam(this.value);getStadium(this.value);">
                                <option value="Mumbai">MI</option>
                                <option value="Kolkata">KKR</option>
                                <option value="Bangalore">RCB</option>
                                <option value="Pune">CSK</option>
                                <option value="Jaipur">RR</option>
                                <option value="Delhi">DD</option>
                                <option value="Dharamshala">KXIP</option>
                                <option value="Hyderabad">SRH</option>
                            </select>
                        </div>
                    </div>
                    <br>
                    <br>
<!--                    <div class="form-group">-->
<!--                        <div class="form-group">-->
<!--                             <label class="control-label">City</label>-->

<!--                            <div>-->
<!--                            <input type="text" value="stadium city" name="city" id="city" readonly/>-->
<!--                            </div>-->
<!--                            </div>-->
<!--                    </div>-->
                    <div class="form-group">
                        <label class="control-label" for="id_venue">Venue</label>

                        <div class=" ">
                            <select name="venue" class=" form-control" id="id_venue">
<!--                                <option value="1">Hyderabad</option>-->
                                 <option value="Hyderabad">Hyderabad</option>
                                <option value="Pune">Pune</option>
                                <option value="Rajkot">Rajkot</option>
                                <option value="Indore">Indore</option>
                                <option value="Bangalore">Bangalore</option>
                                <option value="Mumbai">Mumbai</option>
                                <option value="Delhi">Delhi</option>
                                <option value="Chennai">Chennai</option>
                                <option value="Sharjah">Sharjah</option>
                                <option value="Ranchi">Ranchi</option>
                                <option value="Patna">Patna</option>
                                <option value="Kolkata">Kolkata</option>
                                <option value="Chandigarh">Chandigarh</option>
                                <option value="Kanpur">Kanpur</option>
                                <option value="Jaipur">Jaipur</option>
                                <option value="Ahmedabad">Ahmedabad</option>
                                <option value="Cuttack">Cuttack</option>
                                <option value="Nagpur">Nagpur</option>
                                <option value="Dharamsala">Dharamsala</option>
                                <option value="Kochi">Kochi</option>
                                <option value="Visakhapatnam">Visakhapatnam</option>
                                <option value="Raipur">Raipur</option>
                            </select>
                        </div>

                    </div>
                    <br>
                    <br>
                    <div class="form-group">
                        <label class="control-label">Toss won by</label>
                        <div class=" ">
                            <select name="toss_win" class=" form-control" id="toss" onmousedown="whichTeamHasWonToss()" required>
                                <option selected disabled>Team who won the toss</option>
                            </select>
                        </div>

                    </div>
                    <br>
                    <br>
                    <div class="form-group">
                        <label class="control-label" >Decision of the toss </label>
                        <div class=" ">
                            <select name="decision" class=" form-control" id="id_toss">
                                <option value="Bat">Batting</option>
                                <option value="Field">Fielding</option>
                            </select>
                        </div>

                    </div>
                    <br>
                    <br>

                    <button type="submit" class="btn btn-success btn-block" style="width:70%">Submit</button>
                    <button type="reset" class="btn btn-info btn-block" id="reset" style="width:70%">Reset</button>

                </div>


            </form>
            <br>
        </div>
    </div>
    <!-- //about -->
    <!-- wthree-mid -->
    <div class="wthree-mid jarallax">
        <div class="container">
            <h3>Each run matters..</h3>
            <p>Indian Premier League was started in the year 2008 and then there was no seeing back... </p>
        </div>
    </div>

    <a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover"
                                                                             style="opacity: 1;"> </span></a>
</div>
<!-- //smooth scrolling -->
<script type='text/javascript' src="{% static 'js/jquery-2.2.3.min.js' %}"></script>

<script type="text/javascript" src="../static/js/javaScriptFunction.js"></script>


<!-- start-smoth-scrolling -->
<script src="{% static 'js/jarallax.js' %}"></script>
<script type="text/javascript">
		/* init Jarallax */
		$('.jarallax').jarallax({
			speed: 0.5,
			imgWidth: 1366,
			imgHeight: 768
		})




</script>
<!-- //Owl-Carousel-JavaScript -->
<script type="text/javascript" src="{% static 'js/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'js/easing.js' %}"></script>
<script type="text/javascript">
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();
				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 1000);
			});
		});




</script>
<!-- start-smoth-scrolling -->
<!-- here stars scrolling icon -->
<script type="text/javascript">
		$(document).ready(function () {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
				};
			*/

			$().UItoTop({
				easingType: 'easeOutQuart'
			});

		});




</script>
<!-- //here ends scrolling icon -->


<!--js for bootstrap working-->
<script src="{% static 'js/bootstrap.js' %}"></script>
<!-- //for bootstrap working -->
</body>
</html>

web/fourth_umpire/templates/fourth_umpire/graph_.html

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Bokeh Scatter Plots</title>
   <link rel="stylesheet" href="http://cdn.pydata.org/bokeh/release/bokeh-0.9.0.min.css" type="text/css" />
 </head>
 <body>

    {% if graph %}
<div style="width:600;height:500">
{{ graph|safe }}
</div>
 {{ script | safe }}
{% endif %}
</body>
    <script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-0.9.0.min.js"></script>

</html>